"""Add Entitys

Revision ID: 0eab0bd7671d
Revises: 337f917241f2
Create Date: 2022-04-10 11:17:12.663456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eab0bd7671d'
down_revision = '337f917241f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_model_meta',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('model_name', sa.String(length=255), nullable=True, comment='模型名称'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='模型Id'),
    sa.Column('last_heart_beat', sa.DateTime(timezone=True), nullable=True, comment='心跳'),
    sa.Column('last_train_at', sa.DateTime(timezone=True), nullable=True, comment='上次训练时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_st_model_meta_model_id'), 'st_model_meta', ['model_id'], unique=True)
    op.create_table('st_search_log_detail_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('search_log_id', sa.String(length=40), nullable=True, comment='搜索记录'),
    sa.Column('model_id', sa.String(length=40), nullable=True, comment='用户输入'),
    sa.Column('result_song_id', sa.String(length=40), nullable=True, comment='结果id'),
    sa.Column('result_confidence', sa.Float(), nullable=True, comment='结果置信度（模型）'),
    sa.Column('user_feedback', sa.Float(), nullable=True, comment='用户反馈'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_search_log_detail_history_begin_transaction_id'), 'st_search_log_detail_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_history_end_transaction_id'), 'st_search_log_detail_history', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_history_model_id'), 'st_search_log_detail_history', ['model_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_history_result_song_id'), 'st_search_log_detail_history', ['result_song_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_history_search_log_id'), 'st_search_log_detail_history', ['search_log_id'], unique=False)
    op.create_table('st_search_log_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('search_text', sa.String(length=255), nullable=True, comment='用户输入'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True, comment='查询时间'),
    sa.Column('user_meta', sa.String(length=1000), nullable=True, comment='用户信息'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_search_log_history_begin_transaction_id'), 'st_search_log_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_history_end_transaction_id'), 'st_search_log_history', ['end_transaction_id'], unique=False)
    op.create_table('st_songs_source_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='标题'),
    sa.Column('author', sa.String(length=40), nullable=True, comment='作者'),
    sa.Column('dynasty', sa.String(length=20), nullable=True, comment='朝代'),
    sa.Column('content', sa.String(length=1000), nullable=True, comment='正文'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_songs_source_history_begin_transaction_id'), 'st_songs_source_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_songs_source_history_end_transaction_id'), 'st_songs_source_history', ['end_transaction_id'], unique=False)
    op.create_table('st_search_log',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('search_text', sa.String(length=255), nullable=True, comment='用户输入'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True, comment='查询时间'),
    sa.Column('user_meta', sa.String(length=1000), nullable=True, comment='用户信息'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_search_log_detail',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('search_log_id', sa.String(length=40), nullable=True, comment='搜索记录'),
    sa.Column('model_id', sa.String(length=40), nullable=True, comment='用户输入'),
    sa.Column('result_song_id', sa.String(length=40), nullable=True, comment='结果id'),
    sa.Column('result_confidence', sa.Float(), nullable=True, comment='结果置信度（模型）'),
    sa.Column('user_feedback', sa.Float(), nullable=True, comment='用户反馈'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_st_search_log_detail_model_id'), 'st_search_log_detail', ['model_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_result_song_id'), 'st_search_log_detail', ['result_song_id'], unique=False)
    op.create_index(op.f('ix_st_search_log_detail_search_log_id'), 'st_search_log_detail', ['search_log_id'], unique=False)
    op.create_table('st_songs_source',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='标题'),
    sa.Column('author', sa.String(length=40), nullable=True, comment='作者'),
    sa.Column('dynasty', sa.String(length=20), nullable=True, comment='朝代'),
    sa.Column('content', sa.String(length=1000), nullable=True, comment='正文'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('st_songs_source')
    op.drop_index(op.f('ix_st_search_log_detail_search_log_id'), table_name='st_search_log_detail')
    op.drop_index(op.f('ix_st_search_log_detail_result_song_id'), table_name='st_search_log_detail')
    op.drop_index(op.f('ix_st_search_log_detail_model_id'), table_name='st_search_log_detail')
    op.drop_table('st_search_log_detail')
    op.drop_table('st_search_log')
    op.drop_index(op.f('ix_st_songs_source_history_end_transaction_id'), table_name='st_songs_source_history')
    op.drop_index(op.f('ix_st_songs_source_history_begin_transaction_id'), table_name='st_songs_source_history')
    op.drop_table('st_songs_source_history')
    op.drop_index(op.f('ix_st_search_log_history_end_transaction_id'), table_name='st_search_log_history')
    op.drop_index(op.f('ix_st_search_log_history_begin_transaction_id'), table_name='st_search_log_history')
    op.drop_table('st_search_log_history')
    op.drop_index(op.f('ix_st_search_log_detail_history_search_log_id'), table_name='st_search_log_detail_history')
    op.drop_index(op.f('ix_st_search_log_detail_history_result_song_id'), table_name='st_search_log_detail_history')
    op.drop_index(op.f('ix_st_search_log_detail_history_model_id'), table_name='st_search_log_detail_history')
    op.drop_index(op.f('ix_st_search_log_detail_history_end_transaction_id'), table_name='st_search_log_detail_history')
    op.drop_index(op.f('ix_st_search_log_detail_history_begin_transaction_id'), table_name='st_search_log_detail_history')
    op.drop_table('st_search_log_detail_history')
    op.drop_index(op.f('ix_st_model_meta_model_id'), table_name='st_model_meta')
    op.drop_table('st_model_meta')
    # ### end Alembic commands ###
