"""create Messsage

Revision ID: 1b42d43c1bcb
Revises: bae7defdec5f
Create Date: 2022-04-23 23:50:27.026544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b42d43c1bcb'
down_revision = 'bae7defdec5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_message_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('receiver', sa.String(length=40), nullable=False, comment='接收人'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='标题'),
    sa.Column('content', sa.String(length=1000), nullable=True, comment='正文'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('checked', sa.Boolean(), nullable=False, comment='已查看'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_message_history_begin_transaction_id'), 'st_message_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_message_history_end_transaction_id'), 'st_message_history', ['end_transaction_id'], unique=False)
    op.create_table('st_message',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('receiver', sa.String(length=40), nullable=False, comment='接收人'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='标题'),
    sa.Column('content', sa.String(length=1000), nullable=True, comment='正文'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('checked', sa.Boolean(), nullable=False, comment='已查看'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('st_message')
    op.drop_index(op.f('ix_st_message_history_end_transaction_id'), table_name='st_message_history')
    op.drop_index(op.f('ix_st_message_history_begin_transaction_id'), table_name='st_message_history')
    op.drop_table('st_message_history')
    # ### end Alembic commands ###
