"""add int_id

Revision ID: 23fef7170283
Revises: 0eab0bd7671d
Create Date: 2022-04-23 09:28:37.380495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fef7170283'
down_revision = '0eab0bd7671d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence songs_search_int_id_autoincrement increment by 1 minvalue 1 no maxvalue start with 1;")
    op.add_column('st_songs_source', sa.Column('int_id', sa.Integer(), sa.Sequence('songs_search_int_id_autoincrement'), nullable=True, comment='数字id'))
    op.create_index(op.f('ix_st_songs_source_int_id'), 'st_songs_source', ['int_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_st_songs_source_int_id'), table_name='st_songs_source')
    op.drop_column('st_songs_source', 'int_id')
    op.execute("drop sequence songs_search_int_id_autoincrement;")
    # ### end Alembic commands ###
