"""Set sequence for song_source.int_id

Revision ID: bae7defdec5f
Revises: 1674a3b0cce9
Create Date: 2022-04-23 11:19:29.956990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae7defdec5f'
down_revision = '1674a3b0cce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
